# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da717b977c258f9f324b031eaef3adae4e5e4094bec4e150c179630c002cd3f6b20c2c0457caabab4ccab83d515bdc73d1dee9befb050106875c7003e6f90dfe

test:
  secret_key_base: d284c3aceeffef52ed59862e6cc448b3a6df7676eb1c6d9bfa4b83b773e3804d821ff872c242fd3c48d8460f4251586e8d3e52748d21db9c275b66b2bec8ea34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
